name: getting_started_guide
version: 1.0.0
description: Dart getting started guide.
author: Uday Hiwarale <thatisuday@gmail.com>
repository: https://github.com/thatisuday/dart-getting-started-guide
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  http: ^0.12.0+2
  meta: ^1.1.7
  glob: ^1.0.3
  process_run: ^0.10.3